/**
 * Groba preslikava država → celina, za statistiko na profilu in za section
 * headerje v ListScreen (razvrščanje "po celini") – vrednosti so zato v
 * angleščini, saj so lahko neposredno prikazane uporabniku. Ne shranjujemo
 * celine neposredno (ni stolpca v bazi), zato jo izpeljemo iz besedila v
 * `country` – uporabnik ga vpiše prosto, zato podpiramo tako slovenska kot
 * angleška imena najpogostejših držav. Neznana država pade v "Other".
 */
const CONTINENT_BY_COUNTRY: Record<string, string> = {
  // Evropa
  slovenija: 'Europe',
  slovenia: 'Europe',
  italija: 'Europe',
  italy: 'Europe',
  hrvaska: 'Europe',
  hrvaška: 'Europe',
  croatia: 'Europe',
  avstrija: 'Europe',
  austria: 'Europe',
  nemcija: 'Europe',
  nemčija: 'Europe',
  germany: 'Europe',
  francija: 'Europe',
  france: 'Europe',
  spanija: 'Europe',
  španija: 'Europe',
  spain: 'Europe',
  portugalska: 'Europe',
  portugal: 'Europe',
  svica: 'Europe',
  švica: 'Europe',
  switzerland: 'Europe',
  'velika britanija': 'Europe',
  'zdruzeno kraljestvo': 'Europe',
  'združeno kraljestvo': 'Europe',
  'united kingdom': 'Europe',
  uk: 'Europe',
  england: 'Europe',
  irska: 'Europe',
  ireland: 'Europe',
  nizozemska: 'Europe',
  netherlands: 'Europe',
  belgija: 'Europe',
  belgium: 'Europe',
  poljska: 'Europe',
  poland: 'Europe',
  ceska: 'Europe',
  češka: 'Europe',
  czechia: 'Europe',
  'czech republic': 'Europe',
  slovaska: 'Europe',
  slovaška: 'Europe',
  slovakia: 'Europe',
  madzarska: 'Europe',
  madžarska: 'Europe',
  hungary: 'Europe',
  grcija: 'Europe',
  grčija: 'Europe',
  greece: 'Europe',
  svedska: 'Europe',
  švedska: 'Europe',
  sweden: 'Europe',
  norveska: 'Europe',
  norveška: 'Europe',
  norway: 'Europe',
  danska: 'Europe',
  denmark: 'Europe',
  finska: 'Europe',
  finland: 'Europe',
  islandija: 'Europe',
  iceland: 'Europe',
  romunija: 'Europe',
  romania: 'Europe',
  bolgarija: 'Europe',
  bulgaria: 'Europe',
  srbija: 'Europe',
  serbia: 'Europe',
  bosna: 'Europe',
  'bosna in hercegovina': 'Europe',
  'crna gora': 'Europe',
  montenegro: 'Europe',
  'severna makedonija': 'Europe',
  albanija: 'Europe',
  albania: 'Europe',
  ukrajina: 'Europe',
  ukraine: 'Europe',
  rusija: 'Europe',
  russia: 'Europe',

  // Azija
  turcija: 'Asia',
  turčija: 'Asia',
  turkey: 'Asia',
  kitajska: 'Asia',
  china: 'Asia',
  japonska: 'Asia',
  japan: 'Asia',
  indija: 'Asia',
  india: 'Asia',
  tajska: 'Asia',
  thailand: 'Asia',
  vietnam: 'Asia',
  indonezija: 'Asia',
  indonesia: 'Asia',
  filipini: 'Asia',
  philippines: 'Asia',
  malezija: 'Asia',
  malaysia: 'Asia',
  singapur: 'Asia',
  singapore: 'Asia',
  'juzna koreja': 'Asia',
  'južna koreja': 'Asia',
  'south korea': 'Asia',
  izrael: 'Asia',
  israel: 'Asia',
  nepal: 'Asia',

  // Severna Amerika
  zda: 'North America',
  'united states': 'North America',
  usa: 'North America',
  kanada: 'North America',
  canada: 'North America',
  mehika: 'North America',
  mexico: 'North America',
  kostarika: 'North America',
  'costa rica': 'North America',

  // Južna Amerika
  argentina: 'South America',
  brazilija: 'South America',
  brazil: 'South America',
  cile: 'South America',
  čile: 'South America',
  chile: 'South America',
  kolumbija: 'South America',
  colombia: 'South America',
  peru: 'South America',
  urugvaj: 'South America',
  uruguay: 'South America',
  ekvador: 'South America',
  ecuador: 'South America',
  bolivija: 'South America',
  bolivia: 'South America',
  venezuela: 'South America',

  // Afrika
  egipt: 'Africa',
  egypt: 'Africa',
  maroko: 'Africa',
  morocco: 'Africa',
  'juzna afrika': 'Africa',
  'južna afrika': 'Africa',
  'south africa': 'Africa',
  kenija: 'Africa',
  kenya: 'Africa',
  tanzanija: 'Africa',
  tanzania: 'Africa',
  tunizija: 'Africa',
  tunisia: 'Africa',

  // Oceanija
  avstralija: 'Oceania',
  australia: 'Oceania',
  'nova zelandija': 'Oceania',
  'new zealand': 'Oceania',
};

/** Vrne celino za dano državo (po imenu, brez upoštevanja velikih/malih črk). */
export function continentForCountry(country: string): string {
  const key = country.trim().toLowerCase();
  return CONTINENT_BY_COUNTRY[key] ?? 'Other';
}
