/**
 * Groba preslikava država → celina, za statistiko na profilu.
 * Ne shranjujemo celine neposredno (ni stolpca v bazi), zato jo izpeljemo
 * iz besedila v `country` – uporabnik ga vpiše prosto, zato podpiramo tako
 * slovenska kot angleška imena najpogostejših držav. Neznana država pade v "Drugo".
 */
const CONTINENT_BY_COUNTRY: Record<string, string> = {
  // Evropa
  slovenija: 'Evropa',
  slovenia: 'Evropa',
  italija: 'Evropa',
  italy: 'Evropa',
  hrvaska: 'Evropa',
  hrvaška: 'Evropa',
  croatia: 'Evropa',
  avstrija: 'Evropa',
  austria: 'Evropa',
  nemcija: 'Evropa',
  nemčija: 'Evropa',
  germany: 'Evropa',
  francija: 'Evropa',
  france: 'Evropa',
  spanija: 'Evropa',
  španija: 'Evropa',
  spain: 'Evropa',
  portugalska: 'Evropa',
  portugal: 'Evropa',
  svica: 'Evropa',
  švica: 'Evropa',
  switzerland: 'Evropa',
  'velika britanija': 'Evropa',
  'zdruzeno kraljestvo': 'Evropa',
  'združeno kraljestvo': 'Evropa',
  'united kingdom': 'Evropa',
  uk: 'Evropa',
  england: 'Evropa',
  irska: 'Evropa',
  ireland: 'Evropa',
  nizozemska: 'Evropa',
  netherlands: 'Evropa',
  belgija: 'Evropa',
  belgium: 'Evropa',
  poljska: 'Evropa',
  poland: 'Evropa',
  ceska: 'Evropa',
  češka: 'Evropa',
  czechia: 'Evropa',
  'czech republic': 'Evropa',
  slovaska: 'Evropa',
  slovaška: 'Evropa',
  slovakia: 'Evropa',
  madzarska: 'Evropa',
  madžarska: 'Evropa',
  hungary: 'Evropa',
  grcija: 'Evropa',
  grčija: 'Evropa',
  greece: 'Evropa',
  svedska: 'Evropa',
  švedska: 'Evropa',
  sweden: 'Evropa',
  norveska: 'Evropa',
  norveška: 'Evropa',
  norway: 'Evropa',
  danska: 'Evropa',
  denmark: 'Evropa',
  finska: 'Evropa',
  finland: 'Evropa',
  islandija: 'Evropa',
  iceland: 'Evropa',
  romunija: 'Evropa',
  romania: 'Evropa',
  bolgarija: 'Evropa',
  bulgaria: 'Evropa',
  srbija: 'Evropa',
  serbia: 'Evropa',
  bosna: 'Evropa',
  'bosna in hercegovina': 'Evropa',
  'crna gora': 'Evropa',
  montenegro: 'Evropa',
  'severna makedonija': 'Evropa',
  albanija: 'Evropa',
  albania: 'Evropa',
  ukrajina: 'Evropa',
  ukraine: 'Evropa',
  rusija: 'Evropa',
  russia: 'Evropa',

  // Azija
  turcija: 'Azija',
  turčija: 'Azija',
  turkey: 'Azija',
  kitajska: 'Azija',
  china: 'Azija',
  japonska: 'Azija',
  japan: 'Azija',
  indija: 'Azija',
  india: 'Azija',
  tajska: 'Azija',
  thailand: 'Azija',
  vietnam: 'Azija',
  indonezija: 'Azija',
  indonesia: 'Azija',
  filipini: 'Azija',
  philippines: 'Azija',
  malezija: 'Azija',
  malaysia: 'Azija',
  singapur: 'Azija',
  singapore: 'Azija',
  'juzna koreja': 'Azija',
  'južna koreja': 'Azija',
  'south korea': 'Azija',
  izrael: 'Azija',
  israel: 'Azija',
  nepal: 'Azija',

  // Severna Amerika
  zda: 'Severna Amerika',
  'united states': 'Severna Amerika',
  usa: 'Severna Amerika',
  kanada: 'Severna Amerika',
  canada: 'Severna Amerika',
  mehika: 'Severna Amerika',
  mexico: 'Severna Amerika',
  kostarika: 'Severna Amerika',
  'costa rica': 'Severna Amerika',

  // Južna Amerika
  argentina: 'Južna Amerika',
  brazilija: 'Južna Amerika',
  brazil: 'Južna Amerika',
  cile: 'Južna Amerika',
  čile: 'Južna Amerika',
  chile: 'Južna Amerika',
  kolumbija: 'Južna Amerika',
  colombia: 'Južna Amerika',
  peru: 'Južna Amerika',
  urugvaj: 'Južna Amerika',
  uruguay: 'Južna Amerika',
  ekvador: 'Južna Amerika',
  ecuador: 'Južna Amerika',
  bolivija: 'Južna Amerika',
  bolivia: 'Južna Amerika',
  venezuela: 'Južna Amerika',

  // Afrika
  egipt: 'Afrika',
  egypt: 'Afrika',
  maroko: 'Afrika',
  morocco: 'Afrika',
  'juzna afrika': 'Afrika',
  'južna afrika': 'Afrika',
  'south africa': 'Afrika',
  kenija: 'Afrika',
  kenya: 'Afrika',
  tanzanija: 'Afrika',
  tanzania: 'Afrika',
  tunizija: 'Afrika',
  tunisia: 'Afrika',

  // Oceanija
  avstralija: 'Oceanija',
  australia: 'Oceanija',
  'nova zelandija': 'Oceanija',
  'new zealand': 'Oceanija',
};

/** Vrne celino za dano državo (po imenu, brez upoštevanja velikih/malih črk). */
export function continentForCountry(country: string): string {
  const key = country.trim().toLowerCase();
  return CONTINENT_BY_COUNTRY[key] ?? 'Drugo';
}
